import { AppState } from "../types";

export const initialAppState: AppState = {
  user: {
    id: "usr_trial_8841",
    email: "vapidemo2@gmail.com",
    role: "user",
    plan: "Trial",
    trialEndsAt: "2026-10-02T12:00:00Z",
    limits: {
      hashtagsWeek: 10,
      leadsDay: 10,
      dmsHour: 200,
    },
    usage: {
      hashtagsUsed: 5,
      leadsToday: 0,
      dmsSentToday: 0,
    },
  },
  setupDismissed: false,
  onboarding: [
    {
      id: 1,
      title: "Hashtags configured",
      helper: "Hashtags are how we find your leads",
      action: "Manage",
      destination: "/pipeline/instagram/hashtags/setup",
      completed: true,
    },
    {
      id: 2,
      title: "Filtering criteria set",
      helper: "Define who qualifies as a lead",
      action: "Edit",
      destination: "/pipeline/instagram/filters",
      completed: true,
    },
    {
      id: 3,
      title: "Generate your first leads",
      helper: "Open Hashtag Leads and click Start Lead Generation",
      action: "Go to Leads",
      destination: "/pipeline/instagram/hashtags/leads",
      completed: false,
    },
    {
      id: 4,
      title: "DM template created",
      helper: "Personalized messages to send leads",
      action: "Set up",
      destination: "/outreach/templates",
      completed: true,
    },
    {
      id: 5,
      title: "Competitors added",
      helper: "Find leads from competitor followers",
      action: "Add",
      destination: "/pipeline/instagram/competitors/setup",
      completed: false,
    },
  ],
  businessProfile: {
    description: "B2B outbound sales acceleration and automated pipeline software for agency owners, SaaS founders, and growth marketing teams seeking qualified inbound meetings.",
    targetRegion: "United States, United Kingdom, Canada, Australia",
  },
  hashtags: [
    {
      id: "ht_1",
      tag: "#saasgrowth",
      source: "ai",
      validationScore: 94,
      postsCount: "1.2M",
      relevanceScore: 96,
      active: true,
    },
    {
      id: "ht_2",
      tag: "#b2bmarketing",
      source: "ai",
      validationScore: 91,
      postsCount: "850k",
      relevanceScore: 92,
      active: true,
    },
    {
      id: "ht_3",
      tag: "#ecommercebusiness",
      source: "ai",
      validationScore: 88,
      postsCount: "2.4M",
      relevanceScore: 85,
      active: true,
    },
    {
      id: "ht_4",
      tag: "#agencygrowth",
      source: "ai",
      validationScore: 86,
      postsCount: "320k",
      relevanceScore: 89,
      active: true,
    },
    {
      id: "ht_5",
      tag: "#growthhacking",
      source: "ai",
      validationScore: 90,
      postsCount: "1.9M",
      relevanceScore: 91,
      active: true,
    },
  ],
  competitors: [
    {
      id: "comp_1",
      username: "growthfunder",
      name: "Growth Funder Global",
      followersCount: "48.2k",
      addedAt: "2026-09-20T10:00:00Z",
      lockedUntil: "2026-09-27T10:00:00Z",
    },
    {
      id: "comp_2",
      username: "hyperlead_ai",
      name: "HyperLead Automation",
      followersCount: "32.1k",
      addedAt: "2026-09-21T14:30:00Z",
      lockedUntil: "2026-09-28T14:30:00Z",
    },
  ],
  filters: {
    contentThemes: ["business", "marketing", "startup", "agency", "saas", "founder"],
    followerRange: {
      min: 1000,
      max: 100000,
      minEnabled: true,
      maxEnabled: true,
    },
    targetLocations: ["United States", "United Kingdom", "Canada", "Europe"],
    languages: ["english"],
    blockedKeywords: ["crypto", "nft", "forex", "dm for collab", "sugar daddy", "cash giveaway"],
    blockedCategories: ["Adult Content", "Gambling", "Multi-Level Marketing"],
    mustHaveEmail: false,
    mustHavePhone: false,
    websiteRequirement: "with_link",
  },
  instagramLeads: [
    {
      id: "ig_1",
      username: "alex.growthlab",
      name: "Alex Rivera",
      bio: "Founder @ScaleVibe | Helping 7-figure agency owners scale client acquisition with AI systems. ?? alex@scalevibe.io",
      followers: 14200,
      engagement: "3.4%",
      category: "Marketing Agency",
      location: "Miami, Florida",
      email: "alex@scalevibe.io",
      source: "hashtag",
      sourceRef: "#agencygrowth",
      decision: "matched",
      foundAt: "2026-09-25T08:15:00Z",
      generatedDm: "Hey Alex! Loved your recent breakdown on agency scaling bottlenecks. We built an AI pipeline specifically for 7-figure agencies to automate lead research without sacrificing personalization. Worth a 2-min look?",
      generatedEmail: "Hi Alex,\n\nI noticed how ScaleVibe is helping agency founders streamline acquisition. Our platform maps high-intent accounts and qualifies them automatically.\n\nWould you be open to seeing a 90-second demo for your team?\n\nBest,\nDevon",
      dmSent: true,
      emailSent: false,
      replied: true,
      opened: true,
    },
    {
      id: "ig_2",
      username: "sarah.dtchacks",
      name: "Sarah Chen",
      bio: "DTC Growth Advisor | Scaling Shopify stores from $50k to $500k/mo. Podcast host @EcommercePulse.",
      followers: 28500,
      engagement: "4.1%",
      category: "E-Commerce",
      location: "Austin, Texas",
      email: "sarah@dtchacks.co",
      source: "competitor",
      sourceRef: "@growthfunder",
      decision: "matched",
      foundAt: "2026-09-25T09:00:00Z",
      generatedDm: "Hey Sarah! Saw your recent podcast episode on influencer seeding. We have an automated system that scouts micro-influencer profiles matching exact engagement benchmarks. Thought you might find it useful!",
      generatedEmail: "Hey Sarah,\n\nBig fan of your EcommercePulse episodes! We built an automated prospect engine that pulls verified DTC brand founders and micro-creators.\n\nCould I send over a quick case study?\n\nCheers,\nDevon",
      dmSent: true,
      emailSent: true,
      replied: true,
      opened: true,
    },
    {
      id: "ig_3",
      username: "marcus_saasify",
      name: "Marcus Vance",
      bio: "VP Growth @CloudGrid | Ex-Segment, Hubspot | Writing about B2B pipeline velocity & product-led outbound.",
      followers: 8900,
      engagement: "2.8%",
      category: "Software & Technology",
      location: "San Francisco, CA",
      email: "marcus@cloudgrid.tech",
      source: "hashtag",
      sourceRef: "#saasgrowth",
      decision: "matched",
      foundAt: "2026-09-25T10:10:00Z",
      generatedDm: "Hey Marcus, your post on product-led outbound resonated big time. We designed a dual Instagram + Maps discovery workflow that catches high-intent B2B accounts. Would love your feedback on the flow!",
      generatedEmail: "Hi Marcus,\n\nEnjoyed your framework on pipeline velocity. Our tool combines multi-channel discovery with AI qualification to feed SDRs verified prospects.\n\nOpen to exchanging thoughts this week?\n\nBest,\nDevon",
      dmSent: false,
      emailSent: false,
      replied: false,
      opened: false,
    },
    {
      id: "ig_4",
      username: "elena.mediaops",
      name: "Elena Rostova",
      bio: "Performance Marketing Lead @ApexDirect | $12M+ managed ad spend across Meta & TikTok.",
      followers: 41200,
      engagement: "3.9%",
      category: "Advertising",
      location: "New York, NY",
      email: "elena@apexdirect.com",
      source: "hashtag",
      sourceRef: "#b2bmarketing",
      decision: "matched",
      foundAt: "2026-09-25T11:20:00Z",
      generatedDm: "Hi Elena! Incredible numbers with your Meta ad creative series. We help media agencies tap fresh organic prospect pools across niche hashtags. Happy to share a quick preview if curious!",
      generatedEmail: "Hi Elena,\n\nCongrats on the $12M milestone at ApexDirect! We built an outbound system tailored for performance marketing leaders to fill client pipelines without expensive ad spend.\n\nOpen to a quick intro?\n\nBest,\nDevon",
      dmSent: false,
      emailSent: false,
      replied: false,
      opened: false,
    },
    {
      id: "ig_5",
      username: "crypto_moon_signals",
      name: "Crypto Moon VIP",
      bio: "?? 100x Daily Gems | Forex trading | DM FOR COLLAB & PROMO",
      followers: 125000,
      engagement: "0.2%",
      category: "Finance",
      location: "Dubai, UAE",
      email: "promo@cryptomoon.xyz",
      source: "hashtag",
      sourceRef: "#growthhacking",
      decision: "blocked",
      foundAt: "2026-09-25T11:45:00Z",
      generatedDm: "",
      generatedEmail: "",
      dmSent: false,
      emailSent: false,
      replied: false,
      opened: false,
    },
  ],
  mapsLeads: [
    {
      id: "maps_1",
      name: "Apex Digital Media Partners",
      category: "Marketing Agency",
      address: "350 5th Ave, Suite 4800",
      city: "New York, NY 10118",
      phone: "+1 (212) 555-0192",
      website: "https://apexdigitalny.com",
      email: "contact@apexdigitalny.com",
      rating: 4.9,
      reviewsCount: 114,
      revealed: true,
      decision: "matched",
      executives: [
        { name: "David Miller", title: "Managing Partner", email: "david@apexdigitalny.com", linkedin: "linkedin.com/in/davidmiller-apex" },
        { name: "Rachel Green", title: "Head of Client Growth", email: "rachel@apexdigitalny.com" },
      ],
    },
    {
      id: "maps_2",
      name: "Austin Creative Growth Lab",
      category: "Advertising Agency",
      address: "201 Colorado St",
      city: "Austin, TX 78701",
      phone: "+1 (512) 555-0143",
      website: "https://austincreativegrowth.com",
      email: "info@austincreativegrowth.com",
      rating: 4.8,
      reviewsCount: 68,
      revealed: true,
      decision: "matched",
      executives: [
        { name: "Tyler Jenkins", title: "Founder & Creative Director", email: "tyler@austincreativegrowth.com" },
      ],
    },
    {
      id: "maps_3",
      name: "Loopline Brand Architects",
      category: "Design Agency",
      address: "111 W Jackson Blvd",
      city: "Chicago, IL 60604",
      phone: "+1 (312) 555-0188",
      website: "https://looplinebrands.com",
      email: "hello@looplinebrands.com",
      rating: 4.7,
      reviewsCount: 89,
      revealed: false,
      decision: "pending",
      executives: [
        { name: "Claire Dupont", title: "Managing Director" },
      ],
    },
    {
      id: "maps_4",
      name: "Summit Ridge IT & Cloud",
      category: "Software Company",
      address: "800 5th Ave",
      city: "Seattle, WA 98104",
      phone: "+1 (206) 555-0137",
      website: "https://summitridgecloud.io",
      email: "sales@summitridgecloud.io",
      rating: 4.9,
      reviewsCount: 42,
      revealed: false,
      decision: "pending",
      executives: [
        { name: "Sanjay Patel", title: "CEO" },
      ],
    },
  ],
  conversations: [
    {
      id: "conv_1",
      channel: "instagram",
      contactName: "Alex Rivera",
      contactHandle: "@alex.growthlab",
      contactAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
      contactType: "lead",
      needsHuman: false,
      lastActive: "12 mins ago",
      unread: false,
      messages: [
        {
          id: "m_1",
          sender: "me",
          text: "Hey Alex! Loved your recent breakdown on agency scaling bottlenecks. We built an AI pipeline specifically for 7-figure agencies to automate lead research without sacrificing personalization. Worth a 2-min look?",
          timestamp: "Yesterday, 3:14 PM",
        },
        {
          id: "m_2",
          sender: "them",
          text: "Hey Devon! Thanks man. Actually yes, our SDR team spends way too much time sifting through Instagram and Maps manually. How does your qualification filter work?",
          timestamp: "Yesterday, 5:20 PM",
        },
        {
          id: "m_3",
          sender: "ai",
          text: "Our engine uses multi-criteria AI filtering: you define your ICP themes, follower thresholds, and geo-locations, and it evaluates the prospect bio, recent posts, and engagement. Would you like me to generate a 5-lead sample for ScaleVibe?",
          timestamp: "Yesterday, 5:22 PM",
        },
      ],
    },
    {
      id: "conv_2",
      channel: "instagram",
      contactName: "Sarah Chen",
      contactHandle: "@sarah.dtchacks",
      contactAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80",
      contactType: "lead",
      needsHuman: true,
      lastActive: "1 hour ago",
      unread: true,
      messages: [
        {
          id: "m_4",
          sender: "me",
          text: "Hey Sarah! Saw your recent podcast episode on influencer seeding. We have an automated system that scouts micro-influencer profiles matching exact engagement benchmarks. Thought you might find it useful!",
          timestamp: "Sep 24, 11:00 AM",
        },
        {
          id: "m_5",
          sender: "them",
          text: "Interesting! What are your pricing plans if we need about 5,000 lead profiles per month and team access for 3 account managers?",
          timestamp: "1 hour ago",
        },
      ],
    },
    {
      id: "conv_3",
      channel: "email",
      contactName: "David Miller",
      contactHandle: "david@apexdigitalny.com",
      contactAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
      contactType: "lead",
      needsHuman: false,
      lastActive: "3 hours ago",
      unread: false,
      messages: [
        {
          id: "m_6",
          sender: "me",
          text: "Hi David, saw Apex Digital Media's impressive case studies in NYC. We've automated local B2B business discovery and decision-maker contact enrichment. Could I share a 2-minute overview?",
          timestamp: "Sep 23, 9:00 AM",
        },
        {
          id: "m_7",
          sender: "them",
          text: "Hi Devon, sure, please send over your deck or a loom video.",
          timestamp: "Sep 24, 2:15 PM",
        },
      ],
    },
    {
      id: "conv_4",
      channel: "instagram",
      contactName: "Emma Watson",
      contactHandle: "@emma_creative",
      contactAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
      contactType: "user",
      needsHuman: false,
      lastActive: "Yesterday",
      unread: false,
      messages: [
        {
          id: "m_8",
          sender: "them",
          text: "Hi! Are you guys currently accepting affiliate partners for Celestia Leads?",
          timestamp: "Yesterday, 10:10 AM",
        },
        {
          id: "m_9",
          sender: "me",
          text: "Hi Emma! Yes, we offer 30% recurring commissions for agencies and creators. Check out our partner portal or let me know if you want the onboarding link!",
          timestamp: "Yesterday, 10:45 AM",
        },
      ],
    },
  ],
  campaigns: [
    {
      id: "camp_1",
      name: "Q4 Agency Founders - IG DM Sequence",
      channel: "instagram",
      mode: "automated",
      status: "running",
      recipientsCount: 150,
      sentCount: 85,
      repliedCount: 18,
      createdAt: "2026-09-22T08:00:00Z",
    },
    {
      id: "camp_2",
      name: "Local Marketing Agencies - NY/Austin",
      channel: "maps",
      mode: "automated",
      status: "running",
      recipientsCount: 64,
      sentCount: 42,
      repliedCount: 9,
      createdAt: "2026-09-23T11:30:00Z",
    },
    {
      id: "camp_3",
      name: "Competitor Followers Quick Blitz",
      channel: "instagram",
      mode: "manual",
      status: "draft",
      recipientsCount: 25,
      sentCount: 0,
      repliedCount: 0,
      createdAt: "2026-09-25T09:15:00Z",
    },
  ],
  aiReplyRules: {
    businessDefinition: "Celestia Leads provides AI outbound lead generation, automated Instagram hashtag/competitor discovery, Google Maps polygon scraping, and multi-channel outreach.",
    postReplyInstruction: "Thank them warmly, answer their technical or qualification question directly using our core value proposition, and offer a low-friction 10-minute demo or free sample list.",
    stopMessagingCriteria: "If the contact requests unsubscribe, says 'not interested', demonstrates hostility, or states they do not do outbound sales.",
    humanHandoffCriteria: "Flag conversation and alert staff when prospect asks for custom enterprise pricing, contract negotiations, API access, or requests to speak directly with the founder.",
  },
  templates: {
    hashtagDm: "Hey {name}! Loved your recent work in {niche}. We built an AI pipeline specifically for high-growth teams to automate prospect discovery from Instagram and Maps. Worth a 2-min look?",
    hashtagEmail: "Hi {name},\n\nI noticed your focus on {category} at {company}. We developed an AI outreach workflow that sources verified decision-makers and personalizes messaging automatically.\n\nWould you be open to a 3-minute demo video?\n\nBest,\n{your_name}",
    fromName: "Devon Carter",
    companyName: "Celestia Leads",
    competitorDm: "Hey {name}! Saw you follow {competitor} — we built an alternative outbound system designed to get 3x reply rates using multi-channel DM and email sequences. Would love to hear your thoughts!",
  },
  integrations: {
    instagram: {
      connected: false,
      appLabel: "Celestia Production App",
      appId: "",
      appSecret: "",
      token: "",
      webhookConfigured: false,
      verifyToken: "celestia_wh_token_88921",
    },
    gmail: {
      accounts: [
        {
          email: "devon@growthcelestia.com",
          connected: true,
          type: "app_password",
          dailySent: 28,
        },
      ],
    },
  },
  settings: {
    darkMode: false,
    pushNotifications: true,
    dailyLeadsEmail: false,
    cycleExpirationReminder: false,
    automatedLeadGeneration: false,
    automatedWeeklyCycle: false,
  },
};
